"use client";

import { useUser } from '@clerk/nextjs';
import { useEffect, useState } from 'react';
import DashboardSidebar from "@/components/dashboard-sidebar";
import { motion } from "framer-motion";
import Image from "next/image";
import { 
  Upload, 
  FileText, 
  X, 
  Loader2,
  AlertTriangle,
  CheckCircle,
  BarChart3,
  Brain,
  Target,
  Zap,
  HelpCircle
} from "lucide-react";
import { useUsageTracking } from "@/lib/hooks/useUsageTracking";
import UsageTracker from "@/components/usage-tracker";
import { SkeletonPage } from "@/components/skeleton-loader";

// Tooltip component for explanations
const Tooltip = ({ children, content }: { children: React.ReactNode; content: string }) => {
  const [isVisible, setIsVisible] = useState(false);

  return (
    <div className="relative inline-block">
      <div
        onMouseEnter={() => setIsVisible(true)}
        onMouseLeave={() => setIsVisible(false)}
        className="cursor-help"
      >
        {children}
      </div>
      {isVisible && (
        <div className="absolute z-10 w-64 p-2 mt-1 text-xs text-white bg-black/90 backdrop-blur-xl rounded-lg shadow-lg border border-white/20 -left-32 top-full">
          {content}
          <div className="absolute w-2 h-2 bg-black/90 backdrop-blur-xl transform rotate-45 -top-1 left-1/2 -translate-x-1/2"></div>
        </div>
      )}
    </div>
  );
};

// Separate component for detailed analysis to ensure proper re-rendering
const DetailedAnalysis = ({ details }: { details: any }) => {
  return (
    <div className="bg-white/5 backdrop-blur-xl rounded-xl p-4 border border-white/10">
      <h4 className="font-semibold text-white mb-3">Detailed Analysis</h4>
      <div className="grid grid-cols-2 gap-3 text-sm">
        <div className="flex items-center">
          <span className="text-gray-400">Total Words:</span>
          <Tooltip content="The total number of words in the analyzed text. This includes all words regardless of whether they were identified as AI-generated or human-written.">
            <HelpCircle className="w-3 h-3 ml-1 text-gray-500 hover:text-gray-300 cursor-help" />
          </Tooltip>
          <span className="font-medium ml-2 text-white">{details?.textWords ?? 'N/A'}</span>
        </div>
        <div className="flex items-center">
          <span className="text-gray-400">AI Words:</span>
          <Tooltip content="The number of words that were identified as likely generated by AI. Higher numbers indicate more AI-generated content.">
            <HelpCircle className="w-3 h-3 ml-1 text-gray-500 hover:text-gray-300 cursor-help" />
          </Tooltip>
          <span className="font-medium ml-2 text-white">{details?.aiWords ?? 'N/A'}</span>
        </div>
        <div className="flex items-center">
          <span className="text-gray-400">Sentences:</span>
          <Tooltip content="The total number of sentences in the analyzed text. This helps determine the structure and complexity of the writing.">
            <HelpCircle className="w-3 h-3 ml-1 text-gray-500 hover:text-gray-300 cursor-help" />
          </Tooltip>
          <span className="font-medium ml-2 text-white">{details?.sentences ?? 'N/A'}</span>
        </div>
        <div className="flex items-center">
          <span className="text-gray-400">Avg Words/Sentence:</span>
          <Tooltip content="The average number of words per sentence. AI-generated text often has more consistent sentence lengths, while human writing varies more.">
            <HelpCircle className="w-3 h-3 ml-1 text-gray-500 hover:text-gray-300 cursor-help" />
          </Tooltip>
          <span className="font-medium ml-2 text-white">{details?.averageWordsPerSentence ?? 'N/A'}</span>
        </div>
        <div className="flex items-center">
          <span className="text-gray-400">Readability Score:</span>
          <Tooltip content="A score indicating how easy the text is to read. Higher scores (0-100) indicate more readable content. AI-generated text often scores differently than human writing.">
            <HelpCircle className="w-3 h-3 ml-1 text-gray-500 hover:text-gray-300 cursor-help" />
          </Tooltip>
          <span className="font-medium ml-2 text-white">{details?.readabilityScore ?? 'N/A'}</span>
        </div>
        <div className="flex items-center">
          <span className="text-gray-400">Perplexity:</span>
          <Tooltip content="A measure of how predictable the text is. Lower perplexity values indicate more predictable (often AI-generated) text, while higher values suggest more creative human writing.">
            <HelpCircle className="w-3 h-3 ml-1 text-gray-500 hover:text-gray-300 cursor-help" />
          </Tooltip>
          <span className="font-medium ml-2 text-white">{details?.perplexity ?? 'N/A'}</span>
        </div>
      </div>
    </div>
  );
};

export default function AIDetectorPage() {
  const { isLoaded, isSignedIn, user } = useUser();
  const [inputText, setInputText] = useState('');
  const [detectionResult, setDetectionResult] = useState<any>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [uploadedFile, setUploadedFile] = useState<File | null>(null);
  const [isFileProcessing, setIsFileProcessing] = useState(false);
  const [textareaRef, setTextareaRef] = useState<HTMLTextAreaElement | null>(null);
  
  // Usage tracking
  const { } = useUsageTracking();
  const [wordCount, setWordCount] = useState(0);

  useEffect(() => {
    if (isLoaded && !isSignedIn) {
      window.location.href = '/';
    }
  }, [isLoaded, isSignedIn]);

  // Calculate word count when input changes
  useEffect(() => {
    const words = inputText.trim().split(/\s+/).filter(word => word.length > 0).length;
    setWordCount(words);
  }, [inputText]);

  // Auto-resize textarea function
  const autoResizeTextarea = (textarea: HTMLTextAreaElement) => {
    textarea.style.height = 'auto';
    textarea.style.height = textarea.scrollHeight + 'px';
  };

  // Handle text input change with auto-resize
  const handleTextChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setInputText(e.target.value);
    autoResizeTextarea(e.target);
  };

  // Auto-resize textarea when inputText changes (e.g., from file upload)
  useEffect(() => {
    if (textareaRef) {
      autoResizeTextarea(textareaRef);
    }
  }, [inputText, textareaRef]);


  const handleAnalyze = async () => {
    if (!inputText.trim()) return;
    
    setIsAnalyzing(true);
    setDetectionResult(null); // Clear previous results
    
    try {
      const response = await fetch('/api/detect-ai', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          text: inputText.trim()
        }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        
        // Handle word limit error
        if (response.status === 403 && (errorData.error?.includes('exceed') || errorData.upgradeRequired)) {
          const errorMessage = errorData.error || 'Word limit exceeded. Please upgrade to process more words.';
          const upgradeMessage = errorData.upgradeRequired ? ` Consider upgrading to ${errorData.upgradeRequired} plan.` : '';
          throw new Error(errorMessage + upgradeMessage);
        }
        
        throw new Error(errorData.error || 'AI detection failed');
      }

      const result = await response.json();
      // Force re-render by clearing state first
      setDetectionResult(null);
      setTimeout(() => {
        setDetectionResult(result);
      }, 50);
    } catch (error) {
      console.error('AI detection error:', error);
      // Set error state for user feedback
      setDetectionResult({
        error: true,
        message: error instanceof Error ? error.message : 'Failed to analyze text. Please try again.',
        aiProbability: 0,
        humanProbability: 0,
        confidence: 0,
        verdict: 'Analysis Failed',
        isAI: false,
        details: {}
      });
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleFileUpload = async (file: File | null) => {
    if (!file) return;
    
    const validTypes = ['text/plain', 'application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/msword'];
    const isValidFile = validTypes.includes(file.type) || file.name.endsWith('.txt') || file.name.endsWith('.pdf') || file.name.endsWith('.docx') || file.name.endsWith('.doc');
    
    if (isValidFile) {
      setUploadedFile(file);
      setIsFileProcessing(true);
      setDetectionResult(null); // Clear previous results
      
      try {
        // Use AI detection API
        const formData = new FormData();
        formData.append('file', file);

        const response = await fetch('/api/detect-file', {
          method: 'POST',
          body: formData,
        });

        if (!response.ok) {
          let errorMessage = 'File analysis failed';
          
          try {
            const errorData = await response.json();
            errorMessage = errorData.error || errorMessage;
          } catch (e) {
            // If response is not JSON, provide default messages based on status
            if (response.status === 413) {
              errorMessage = 'File is too large. Maximum size is 10MB.';
            } else if (response.status === 400) {
              errorMessage = 'Invalid file format. Please upload PDF, DOCX, DOC, or TXT files only.';
            } else if (response.status === 429) {
              errorMessage = 'Too many requests. Please wait a moment and try again.';
            } else if (response.status >= 500) {
              errorMessage = 'AI detection service is temporarily unavailable. Please try again later.';
            }
          }
          
          throw new Error(errorMessage);
        }

        const result = await response.json();
        // Force re-render by clearing state first
        setDetectionResult(null);
        setTimeout(() => {
          setDetectionResult(result);
        }, 50);
        
        // Also set the extracted text for display
        if (result.rawData?.input_text) {
          setInputText(result.rawData.input_text);
        } else {
          setInputText(`[File: ${file.name}]\n\nFile has been analyzed for AI detection. Results are shown in the analysis panel.`);
        }
        
      } catch (error) {
        console.error('File analysis error:', error);
        setDetectionResult({
          error: true,
          message: error instanceof Error ? error.message : 'Failed to analyze file. Please try again.',
          aiProbability: 0,
          humanProbability: 0,
          confidence: 0,
          verdict: 'Analysis Failed',
          isAI: false,
          details: {}
        });
        setInputText(`[Error analyzing ${file.name}]\n\nFailed to analyze the uploaded file. Please try a different file or copy and paste the text manually.`);
      } finally {
        setIsFileProcessing(false);
      }
    } else {
      alert('Please upload a valid file type (.txt, .pdf, .docx, or .doc)');
    }
  };

  const removeUploadedFile = () => {
    setUploadedFile(null);
    setInputText('');
    setDetectionResult(null);
  };

  if (!isLoaded || !isSignedIn) {
    return (
      <>
        <DashboardSidebar />
        <SkeletonPage type="ai-detector" />
      </>
    );
  }

  return (
    <div className="min-h-screen bg-black">
      <DashboardSidebar />

      {/* Main Content */}
      <div className="lg:pl-64 pt-16 pb-16">
        <div className="max-w-7xl mx-auto px-6">
          <div className="mb-8">
            <h1 className="text-3xl font-bold text-white mb-2">
              AI Detector
            </h1>
            <p className="text-gray-400">
              Analyze text to detect if it was generated by AI or written by humans.
            </p>
          </div>


          {/* Main Interface */}
          <motion.div
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="grid grid-cols-1 xl:grid-cols-2 gap-8 mb-16"
          >
            {/* Input Panel */}
            <div className="bg-white/5 backdrop-blur-xl rounded-xl p-8 shadow-lg border border-white/10">
              <div className="flex items-center space-x-3 mb-6">
                <div className="w-10 h-10 bg-white/20 rounded-xl flex items-center justify-center backdrop-blur-sm">
                  <Brain className="w-5 h-5 text-white" />
                </div>
                <div>
                  <h2 className="text-xl font-bold text-white">Input Text</h2>
                  <p className="text-sm text-gray-400">Paste or upload text to analyze</p>
                </div>
              </div>
              
              <div className="space-y-4">
                {/* File Upload Section */}
                {!uploadedFile ? (
                  <div className="flex items-center justify-between bg-white/5 rounded-lg p-3 border border-white/10 backdrop-blur-sm">
                    <div className="flex items-center space-x-2">
                      <Upload className="w-4 h-4 text-gray-400" />
                      <span className="text-sm text-gray-300">Upload a file (PDF, DOCX, DOC, TXT)</span>
                    </div>
                    <input
                      type="file"
                      accept=".pdf,.docx,.doc,.txt"
                      onChange={(e) => handleFileUpload(e.target.files?.[0] || null)}
                      className="hidden"
                      id="file-upload-input"
                      disabled={isFileProcessing}
                    />
                    <label
                      htmlFor="file-upload-input"
                      className={`px-3 py-1 rounded-lg text-xs font-medium cursor-pointer transition-colors backdrop-blur-sm ${
                        isFileProcessing 
                          ? 'bg-white/10 text-gray-500 cursor-not-allowed' 
                          : 'bg-white/10 hover:bg-white/20 text-white'
                      }`}
                    >
                      {isFileProcessing ? 'Processing...' : 'Choose File'}
                    </label>
                  </div>
                ) : (
                  <div className="bg-white/5 border border-white/10 rounded-lg p-3 backdrop-blur-sm">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center space-x-3 min-w-0 flex-1">
                        <FileText className="w-5 h-5 text-gray-400 flex-shrink-0" />
                        <div className="min-w-0 flex-1">
                          <p className="text-sm font-medium text-white truncate">{uploadedFile.name}</p>
                          <p className="text-xs text-gray-400">
                            {(uploadedFile.size / 1024 / 1024).toFixed(2)} MB
                          </p>
                        </div>
                      </div>
                      <div className="flex items-center space-x-2 flex-shrink-0">
                        <input
                          type="file"
                          accept=".pdf,.docx,.txt"
                          onChange={(e) => handleFileUpload(e.target.files?.[0] || null)}
                          className="hidden"
                          id="file-upload-change"
                        />
                        <label
                          htmlFor="file-upload-change"
                          className="px-3 py-1.5 bg-white/10 hover:bg-white/20 rounded-md text-xs font-medium text-white cursor-pointer transition-colors backdrop-blur-sm"
                        >
                          Change
                        </label>
                        <button
                          onClick={removeUploadedFile}
                          className="p-1.5 hover:bg-white/10 rounded-md transition-colors backdrop-blur-sm"
                        >
                          <X className="w-4 h-4 text-gray-400" />
                        </button>
                      </div>
                    </div>
                    {isFileProcessing && (
                      <div className="mt-3 flex items-center space-x-2">
                        <Loader2 className="w-4 h-4 animate-spin text-white" />
                        <span className="text-sm text-gray-300">Analyzing file with AI Detection...</span>
                      </div>
                    )}
                  </div>
                )}

                <div className="relative">
                  <textarea
                    ref={setTextareaRef}
                    value={inputText}
                    onChange={handleTextChange}
                    className="w-full min-h-32 p-6 bg-white/5 border-2 border-white/20 rounded-2xl resize-none focus:ring-4 focus:ring-white/20 focus:border-white/50 transition-all duration-300 text-white placeholder-gray-500 overflow-hidden backdrop-blur-sm"
                    placeholder="Paste your text here to analyze if it was generated by AI or written by humans..."
                    style={{ height: 'auto' }}
                  />
                  <div className="absolute bottom-4 right-4 text-xs text-gray-300 bg-white/10 backdrop-blur-sm px-2 py-1 rounded-lg border border-white/20">
                    {inputText.length} characters
                  </div>
                </div>
                
                <div className="flex items-center justify-between">
                  <div className="text-sm text-gray-400">
                    {inputText.split(/\s+/).filter(word => word.length > 0).length} words
                  </div>
                  
                  <button
                    onClick={handleAnalyze}
                    disabled={!inputText.trim() || isAnalyzing || isFileProcessing}
                    className="flex items-center space-x-2 px-8 py-3 bg-white hover:bg-gray-100 text-black rounded-xl disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-300 shadow-lg hover:shadow-xl"
                  >
                    {isAnalyzing ? (
                      <Loader2 className="w-5 h-5 animate-spin" />
                    ) : (
                      <Target className="w-5 h-5" />
                    )}
                    <span className="font-semibold">
                      {isAnalyzing ? 'Analyzing with AI...' : 'Analyze Text'}
                    </span>
                  </button>
                </div>
              </div>
            </div>

            {/* Results Panel */}
            <div className="bg-white/5 backdrop-blur-xl rounded-xl p-8 shadow-lg border border-white/10">
              <div className="flex items-center space-x-3 mb-6">
                <div className="w-10 h-10 bg-white/20 rounded-xl flex items-center justify-center backdrop-blur-sm">
                  <BarChart3 className="w-5 h-5 text-white" />
                </div>
                <div>
                  <h2 className="text-xl font-bold text-white">Analysis Results</h2>
                  <p className="text-sm text-gray-400">AI detection analysis</p>
                </div>
              </div>
              
              <div className="space-y-6">
                {detectionResult && detectionResult.error ? (
                  <div className="text-center">
                    <div className="w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-4 bg-red-500/20 backdrop-blur-sm border border-red-500/30">
                      <AlertTriangle className="w-10 h-10 text-red-400" />
                    </div>
                    <h3 className="text-2xl font-bold text-red-400 mb-2">
                      Analysis Failed
                    </h3>
                    <p className="text-white mb-2 text-lg font-medium">
                      {detectionResult.message}
                    </p>
                    {detectionResult.message?.includes('complex') && (
                      <div className="bg-blue-500/10 border border-blue-500/30 rounded-lg p-4 mb-4 text-left backdrop-blur-sm">
                        <p className="text-sm text-blue-300">
                          <strong>💡 Tip:</strong> For complex multi-page documents:
                        </p>
                        <ul className="mt-2 text-sm text-blue-400 space-y-1 list-disc list-inside">
                          <li>Try extracting and analyzing individual sections</li>
                          <li>Copy specific portions of text and analyze them separately</li>
                          <li>Use simpler documents for more accurate results</li>
                        </ul>
                      </div>
                    )}
                    <div className="flex gap-3 justify-center mt-4">
                      <button
                        onClick={() => {
                          setDetectionResult(null);
                          setInputText('');
                          setUploadedFile(null);
                        }}
                        className="px-6 py-2 bg-white/10 hover:bg-white/20 text-white rounded-lg transition-colors backdrop-blur-sm border border-white/20"
                      >
                        Clear
                      </button>
                      <button
                        onClick={inputText.trim() ? handleAnalyze : () => {}}
                        className="px-6 py-2 bg-white hover:bg-gray-100 text-black rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                        disabled={!inputText.trim()}
                      >
                        Try Again
                      </button>
                    </div>
                  </div>
                ) : detectionResult && !detectionResult.error ? (
                      <>
                        {/* Main Result */}
                        <div className="text-center">
                          <div className={`w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-4 backdrop-blur-sm border ${
                            detectionResult.isAI ? 'bg-red-500/20 border-red-500/30' : 'bg-emerald-500/20 border-emerald-500/30'
                          }`}>
                            {detectionResult.isAI ? (
                              <AlertTriangle className="w-10 h-10 text-red-400" />
                            ) : (
                              <CheckCircle className="w-10 h-10 text-emerald-400" />
                            )}
                          </div>
                          <h3 className="text-2xl font-bold text-white mb-2">
                            {detectionResult.verdict}
                          </h3>
                          {detectionResult.fileName && (
                            <p className="text-sm text-gray-400 mb-2">
                              File: {detectionResult.fileName}
                            </p>
                          )}
                          <div className="text-4xl font-bold mb-2">
                            <span className={detectionResult.isAI ? 'text-red-400' : 'text-emerald-400'}>
                              {detectionResult.aiProbability}%
                            </span>
                            <span className="text-gray-400"> AI</span>
                          </div>
                          <p className="text-sm text-gray-400">
                            Confidence: {detectionResult.confidence}%
                          </p>
                        </div>

                    {/* Probability Bars */}
                    <div className="space-y-3">
                      <div>
                        <div className="flex justify-between text-sm mb-1">
                          <span className="text-gray-400">AI Generated</span>
                          <span className="font-medium text-white">{detectionResult.aiProbability}%</span>
                        </div>
                        <div className="w-full bg-white/10 rounded-full h-2 backdrop-blur-sm">
                          <div 
                            className="bg-red-500 h-2 rounded-full transition-all duration-1000"
                            style={{ width: `${detectionResult.aiProbability}%` }}
                          />
                        </div>
                      </div>
                      <div>
                        <div className="flex justify-between text-sm mb-1">
                          <span className="text-gray-400">Human Written</span>
                          <span className="font-medium text-white">{detectionResult.humanProbability}%</span>
                        </div>
                        <div className="w-full bg-white/10 rounded-full h-2 backdrop-blur-sm">
                          <div 
                            className="bg-emerald-500 h-2 rounded-full transition-all duration-1000"
                            style={{ width: `${detectionResult.humanProbability}%` }}
                          />
                        </div>
                      </div>
                    </div>


                        {/* Detailed Analysis */}
                        <DetailedAnalysis details={detectionResult.details} />
                      </>
                ) : (
                  <div className="flex items-center justify-center h-64">
                    <div className="text-center">
                      <div className="w-16 h-16 bg-white/10 rounded-2xl flex items-center justify-center mx-auto mb-4 backdrop-blur-sm border border-white/20">
                        <Target className="w-8 h-8 text-gray-400" />
                      </div>
                      <p className="text-gray-400 font-medium">Analysis results will appear here</p>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </motion.div>

          {/* LLM Models Section */}
          <motion.div
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.4 }}
            className="mt-16"
          >
            <div className="text-center mb-8">
              <h2 className="text-2xl font-bold text-white mb-3">
                Powered by Advanced AI Detection Technology
              </h2>
              <p className="text-gray-400">
                Advanced AI detection technology that identifies content from major language models
              </p>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-5 gap-6 max-w-6xl mx-auto">
              {[
                { name: 'GPT Models', description: 'OpenAI GPT-3, GPT-4, ChatGPT', logo: 'gpt-models-logo.png' },
                { name: 'Grok', description: 'xAI Grok AI Model', logo: 'grok-logo.png' },
                { name: 'Claude', description: 'Anthropic Claude AI', logo: 'claude-logo.png' },
                { name: 'Gemini', description: 'Google Gemini AI', logo: 'gemini-logo.png' },
                { name: 'DeepSeek', description: 'DeepSeek AI Model', logo: 'deepseek-logo.png' }
              ].map((llm, index) => (
                <motion.div
                  key={llm.name}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5, delay: 0.1 * index }}
                  whileHover={{ y: -5, scale: 1.02 }}
                  className="bg-white/5 backdrop-blur-xl rounded-2xl p-6 shadow-xl border border-white/10 hover:bg-white/10 hover:shadow-2xl transition-all duration-300 text-center group"
                >
                  <div className="w-16 h-16 bg-white/10 rounded-2xl flex items-center justify-center mx-auto mb-4 shadow-lg border-2 border-white/20 group-hover:border-white/30 transition-colors backdrop-blur-sm">
                    <Image 
                      src={`/dashboard/ai-detector/${llm.logo}`} 
                      alt={`${llm.name} logo`}
                      width={40}
                      height={40}
                      className="object-contain"
                    />
                  </div>
                  <h3 className="text-lg font-bold text-white mb-2">{llm.name}</h3>
                  <p className="text-sm text-gray-400 mb-4">{llm.description}</p>
                  <div className="flex items-center justify-center bg-emerald-500/20 border border-emerald-500/30 rounded-full px-4 py-2 backdrop-blur-sm">
                    <CheckCircle className="w-4 h-4 text-emerald-400 mr-2" />
                    <span className="text-sm text-emerald-300 font-semibold">Detected</span>
                  </div>
                </motion.div>
              ))}
            </div>
          </motion.div>
        </div>
      </div>
    </div>
  );
}
